### ISSUE TITLE
Launcher force closing 

### ISSUE THREAD

**Issue by NaassomDourado** [crdroidandroid/android_packages_apps_Launcher3#205]
time: 1645488895177
msg: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
stacktrace: java.lang.RuntimeException: Unable to get provider androidx.core.content.FileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
	at android.app.ActivityThread.installProvider(ActivityThread.java:7427)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6939)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6710)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:669)
	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:635)
	at androidx.core.content.FileProvider.attachInfo(FileProvider.java:416)
	at android.app.ActivityThread.installProvider(ActivityThread.java:7422)

Introduced after this: https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/1a6baa49eda9caa092953bcc9196c2c48d778ee4
Reseting to https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/c3c3cf2f555dbd0bd141bfa47796916b808f6732 fix the issue.

**Comment by gwolf2u** [comment]
still happening?

**Comment by NaassomDourado** [comment]
> still happening?

Yes, still happening

**Comment by neobuddy89** [comment]
full log.

**Comment by gwolf2u** [comment]
@NaassomDourado can provide full log?

**Comment by NaassomDourado** [comment]
> @NaassomDourado can provide full log?

Hello, i built some minutes ago and seems fixed. Its not happening anymore.

**Comment by gwolf2u** [comment]
closing issue then
