### ISSUE TITLE
Crash when double tap locking

### ISSUE THREAD

**Issue by PycmShoma** [crdroidandroid/android_packages_apps_Launcher3#274]
Process: com.android.launcher3
PID: 2631
UID: 10207
Flags: 0x24cbbe45
Package: com.android.launcher3 v32 (12)
Foreground: Yes
Process-Runtime: 4497069
Build: Xiaomi/cepheus/cepheus:12/SQ3A.220705.004/1661858696:user/release-keys
Loading-Progress: 1.0

java.lang.SecurityException: Neither user 10207 nor current process has android.permission.DEVICE_POWER.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2426)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.os.IPowerManager$Stub$Proxy.goToSleep(IPowerManager.java:1380)
	at android.os.PowerManager.goToSleep(PowerManager.java:1434)
	at android.os.PowerManager.goToSleep(PowerManager.java:1400)
	at com.android.launcher3.touch.WorkspaceTouchListener.onDoubleTap(WorkspaceTouchListener.java:204)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:614)
	at com.android.launcher3.touch.WorkspaceTouchListener.onTouch(WorkspaceTouchListener.java:95)
	at android.view.View.dispatchTouchEvent(View.java:14595)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3114)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2787)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at com.android.launcher3.views.BaseDragLayer.dispatchTouchEvent(BaseDragLayer.java:304)
	at com.android.launcher3.dragndrop.DragLayer.dispatchTouchEvent(DragLayer.java:216)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2744)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1891)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4202)
	at com.android.launcher3.Launcher.dispatchTouchEvent(Launcher.java:1992)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
	at android.view.View.dispatchPointerEvent(View.java:14858)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6253)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5731)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5788)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5754)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5919)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5762)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5976)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5735)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5788)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5754)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5762)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5735)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8714)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8665)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8634)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8837)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:2195)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2223)
	at com.android.server.power.PowerManagerService$BinderService.goToSleep(PowerManagerService.java:5584)
	at android.os.IPowerManager$Stub.onTransact(IPowerManager.java:639)
	at android.os.Binder.execTransactInternal(Binder.java:1179)

**Comment by gwolf2u** [comment]
this happens on a different user profile from default one?

**Comment by PycmShoma** [comment]
I don't have any users added.
Only default

**Comment by PycmShoma** [comment]
The error disappeared with update 2022.09.02

**Comment by PycmShoma** [comment]
The error disappeared with update 2022.09.02
